//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalServiceHost.RentalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalService.IRentalService")]
    public interface IRentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/AddCar", ReplyAction="http://tempuri.org/IRentalService/AddCarResponse")]
        void AddCar(string regNumber, string brand, int year, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalService/AddCar", ReplyAction="http://tempuri.org/IRentalService/AddCarResponse")]
        System.Threading.Tasks.Task AddCarAsync(string regNumber, string brand, int year, string model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalServiceChannel : RentalServiceHost.RentalService.IRentalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalServiceClient : System.ServiceModel.ClientBase<RentalServiceHost.RentalService.IRentalService>, RentalServiceHost.RentalService.IRentalService {
        
        public RentalServiceClient() {
        }
        
        public RentalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCar(string regNumber, string brand, int year, string model) {
            base.Channel.AddCar(regNumber, brand, year, model);
        }
        
        public System.Threading.Tasks.Task AddCarAsync(string regNumber, string brand, int year, string model) {
            return base.Channel.AddCarAsync(regNumber, brand, year, model);
        }
    }
}
