//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalServiceClient.RentalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://localhost:8080/Customer")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://localhost:8080/Car")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRentedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool IsRented {
            get {
                return this.IsRentedField;
            }
            set {
                if ((this.IsRentedField.Equals(value) != true)) {
                    this.IsRentedField = value;
                    this.RaisePropertyChanged("IsRented");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://localhost:8080/Booking")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentalServiceClient.RentalService.Car RentalCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentalServiceClient.RentalService.Customer RenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentalServiceClient.RentalService.Car RentalCar {
            get {
                return this.RentalCarField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalCarField, value) != true)) {
                    this.RentalCarField = value;
                    this.RaisePropertyChanged("RentalCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RentalServiceClient.RentalService.Customer Renter {
            get {
                return this.RenterField;
            }
            set {
                if ((object.ReferenceEquals(this.RenterField, value) != true)) {
                    this.RenterField = value;
                    this.RaisePropertyChanged("Renter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsReturned {
            get {
                return this.IsReturnedField;
            }
            set {
                if ((this.IsReturnedField.Equals(value) != true)) {
                    this.IsReturnedField = value;
                    this.RaisePropertyChanged("IsReturned");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalService.IRentalServiceTest")]
    public interface IRentalServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCar", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCarResponse")]
        RentalServiceClient.RentalService.AddCarResponse AddCar(RentalServiceClient.RentalService.AddCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCar", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddCarResponse> AddCarAsync(RentalServiceClient.RentalService.AddCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveCar", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveCarResponse")]
        RentalServiceClient.RentalService.RemoveCarResponse RemoveCar(RentalServiceClient.RentalService.RemoveCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveCar", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveCarResponse> RemoveCarAsync(RentalServiceClient.RentalService.RemoveCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCustomerResponse")]
        RentalServiceClient.RentalService.AddCustomerResponse AddCustomer(RentalServiceClient.RentalService.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCustomerResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddCustomerResponse> AddCustomerAsync(RentalServiceClient.RentalService.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/EditCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/EditCustomerResponse")]
        RentalServiceClient.RentalService.EditCustomerResponse EditCustomer(RentalServiceClient.RentalService.EditCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/EditCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/EditCustomerResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.EditCustomerResponse> EditCustomerAsync(RentalServiceClient.RentalService.EditCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveCustomerResponse")]
        RentalServiceClient.RentalService.RemoveCustomerResponse RemoveCustomer(RentalServiceClient.RentalService.RemoveCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveCustomerResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveCustomerResponse> RemoveCustomerAsync(RentalServiceClient.RentalService.RemoveCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/AddBookingResponse")]
        RentalServiceClient.RentalService.AddBookingResponse AddBooking(RentalServiceClient.RentalService.AddBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/AddBookingResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddBookingResponse> AddBookingAsync(RentalServiceClient.RentalService.AddBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveBookingResponse")]
        RentalServiceClient.RentalService.RemoveBookingResponse RemoveBooking(RentalServiceClient.RentalService.RemoveBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/RemoveBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/RemoveBookingResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveBookingResponse> RemoveBookingAsync(RentalServiceClient.RentalService.RemoveBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/ReturnCar", ReplyAction="http://tempuri.org/IRentalServiceTest/ReturnCarResponse")]
        RentalServiceClient.RentalService.ReturnCarResponse ReturnCar(RentalServiceClient.RentalService.ReturnCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/ReturnCar", ReplyAction="http://tempuri.org/IRentalServiceTest/ReturnCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.ReturnCarResponse> ReturnCarAsync(RentalServiceClient.RentalService.ReturnCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/CheckDate", ReplyAction="http://tempuri.org/IRentalServiceTest/CheckDateResponse")]
        RentalServiceClient.RentalService.CheckDateResponse CheckDate(RentalServiceClient.RentalService.CheckDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/CheckDate", ReplyAction="http://tempuri.org/IRentalServiceTest/CheckDateResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.CheckDateResponse> CheckDateAsync(RentalServiceClient.RentalService.CheckDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomers", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomersResponse")]
        RentalServiceClient.RentalService.GetCustomersResponse GetCustomers(RentalServiceClient.RentalService.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomers", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomersResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomersResponse> GetCustomersAsync(RentalServiceClient.RentalService.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerById", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByIdResponse")]
        RentalServiceClient.RentalService.GetCustomerByIdResponse GetCustomerById(RentalServiceClient.RentalService.GetCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerById", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByIdResponse> GetCustomerByIdAsync(RentalServiceClient.RentalService.GetCustomerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomersByName", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomersByNameResponse")]
        RentalServiceClient.RentalService.GetCustomersByNameResponse GetCustomersByName(RentalServiceClient.RentalService.GetCustomersByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomersByName", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomersByNameResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomersByNameResponse> GetCustomersByNameAsync(RentalServiceClient.RentalService.GetCustomersByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerByPhoneNumber", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByPhoneNumberResponse")]
        RentalServiceClient.RentalService.GetCustomerByPhoneNumberResponse GetCustomerByPhoneNumber(RentalServiceClient.RentalService.GetCustomerByPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerByPhoneNumber", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByPhoneNumberResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByPhoneNumberResponse> GetCustomerByPhoneNumberAsync(RentalServiceClient.RentalService.GetCustomerByPhoneNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerByEmail", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByEmailResponse")]
        RentalServiceClient.RentalService.GetCustomerByEmailResponse GetCustomerByEmail(RentalServiceClient.RentalService.GetCustomerByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerByEmail", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerByEmailResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByEmailResponse> GetCustomerByEmailAsync(RentalServiceClient.RentalService.GetCustomerByEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerFromBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerFromBookingResponse")]
        RentalServiceClient.RentalService.GetCustomerFromBookingResponse GetCustomerFromBooking(RentalServiceClient.RentalService.GetCustomerFromBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCustomerFromBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCustomerFromBookingResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerFromBookingResponse> GetCustomerFromBookingAsync(RentalServiceClient.RentalService.GetCustomerFromBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarByReg", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarByRegResponse")]
        RentalServiceClient.RentalService.GetCarByRegResponse GetCarByReg(RentalServiceClient.RentalService.GetCarByRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarByReg", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarByRegResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarByRegResponse> GetCarByRegAsync(RentalServiceClient.RentalService.GetCarByRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByBrand", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByBrandResponse")]
        RentalServiceClient.RentalService.GetCarsByBrandResponse GetCarsByBrand(RentalServiceClient.RentalService.GetCarsByBrandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByBrand", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByBrandResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByBrandResponse> GetCarsByBrandAsync(RentalServiceClient.RentalService.GetCarsByBrandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByYear", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByYearResponse")]
        RentalServiceClient.RentalService.GetCarsByYearResponse GetCarsByYear(RentalServiceClient.RentalService.GetCarsByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByYear", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByYearResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByYearResponse> GetCarsByYearAsync(RentalServiceClient.RentalService.GetCarsByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByModel", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByModelResponse")]
        RentalServiceClient.RentalService.GetCarsByModelResponse GetCarsByModel(RentalServiceClient.RentalService.GetCarsByModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByModel", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByModelResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByModelResponse> GetCarsByModelAsync(RentalServiceClient.RentalService.GetCarsByModelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByIsRented", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByIsRentedResponse")]
        RentalServiceClient.RentalService.GetCarsByIsRentedResponse GetCarsByIsRented(RentalServiceClient.RentalService.GetCarsByIsRentedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarsByIsRented", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarsByIsRentedResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByIsRentedResponse> GetCarsByIsRentedAsync(RentalServiceClient.RentalService.GetCarsByIsRentedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarFromBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarFromBookingResponse")]
        RentalServiceClient.RentalService.GetCarFromBookingResponse GetCarFromBooking(RentalServiceClient.RentalService.GetCarFromBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCarFromBooking", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarFromBookingResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarFromBookingResponse> GetCarFromBookingAsync(RentalServiceClient.RentalService.GetCarFromBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingById", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingByIdResponse")]
        RentalServiceClient.RentalService.GetBookingByIdResponse GetBookingById(RentalServiceClient.RentalService.GetBookingByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingById", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingByIdResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingByIdResponse> GetBookingByIdAsync(RentalServiceClient.RentalService.GetBookingByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCar", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCarResponse")]
        RentalServiceClient.RentalService.GetBookingsByCarResponse GetBookingsByCar(RentalServiceClient.RentalService.GetBookingsByCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCar", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCarResponse> GetBookingsByCarAsync(RentalServiceClient.RentalService.GetBookingsByCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerResponse")]
        RentalServiceClient.RentalService.GetBookingsByCustomerResponse GetBookingsByCustomer(RentalServiceClient.RentalService.GetBookingsByCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomer", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerResponse> GetBookingsByCustomerAsync(RentalServiceClient.RentalService.GetBookingsByCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerEmail", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerEmailResponse")]
        RentalServiceClient.RentalService.GetBookingsByCustomerEmailResponse GetBookingsByCustomerEmail(RentalServiceClient.RentalService.GetBookingsByCustomerEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerEmail", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerEmailResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerEmailResponse> GetBookingsByCustomerEmailAsync(RentalServiceClient.RentalService.GetBookingsByCustomerEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerPhone", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerPhoneResponse")]
        RentalServiceClient.RentalService.GetBookingsByCustomerPhoneResponse GetBookingsByCustomerPhone(RentalServiceClient.RentalService.GetBookingsByCustomerPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerPhone", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByCustomerPhoneResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerPhoneResponse> GetBookingsByCustomerPhoneAsync(RentalServiceClient.RentalService.GetBookingsByCustomerPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByTime", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByTimeResponse")]
        RentalServiceClient.RentalService.GetBookingsByTimeResponse GetBookingsByTime(RentalServiceClient.RentalService.GetBookingsByTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByTime", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByTimeResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByTimeResponse> GetBookingsByTimeAsync(RentalServiceClient.RentalService.GetBookingsByTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByIsNotReturned", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByIsNotReturnedResponse")]
        RentalServiceClient.RentalService.GetBookingsByIsNotReturnedResponse GetBookingsByIsNotReturned(RentalServiceClient.RentalService.GetBookingsByIsNotReturnedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetBookingsByIsNotReturned", ReplyAction="http://tempuri.org/IRentalServiceTest/GetBookingsByIsNotReturnedResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByIsNotReturnedResponse> GetBookingsByIsNotReturnedAsync(RentalServiceClient.RentalService.GetBookingsByIsNotReturnedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCar", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarResponse")]
        RentalServiceClient.RentalService.CarInfo GetCar(RentalServiceClient.RentalService.CarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/GetCar", ReplyAction="http://tempuri.org/IRentalServiceTest/GetCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.CarInfo> GetCarAsync(RentalServiceClient.RentalService.CarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/SaveCar", ReplyAction="http://tempuri.org/IRentalServiceTest/SaveCarResponse")]
        RentalServiceClient.RentalService.SaveCarResponse SaveCar(RentalServiceClient.RentalService.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/SaveCar", ReplyAction="http://tempuri.org/IRentalServiceTest/SaveCarResponse")]
        System.Threading.Tasks.Task<RentalServiceClient.RentalService.SaveCarResponse> SaveCarAsync(RentalServiceClient.RentalService.CarInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string regNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string model;
        
        public AddCarRequest() {
        }
        
        public AddCarRequest(string regNumber, string brand, int year, string model) {
            this.regNumber = regNumber;
            this.brand = brand;
            this.year = year;
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCarResponse {
        
        public AddCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string regNumber;
        
        public RemoveCarRequest() {
        }
        
        public RemoveCarRequest(string regNumber) {
            this.regNumber = regNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCarResponse {
        
        public RemoveCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string phoneNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string emailAddress;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(string firstName, string lastName, string phoneNumber, string emailAddress) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.phoneNumber = phoneNumber;
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCustomerResponse {
        
        public AddCustomerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer customer;
        
        public EditCustomerRequest() {
        }
        
        public EditCustomerRequest(RentalServiceClient.RentalService.Customer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EditCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EditCustomerResponse {
        
        public EditCustomerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int id;
        
        public RemoveCustomerRequest() {
        }
        
        public RemoveCustomerRequest(string firstName, string lastName, int id) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveCustomerResponse {
        
        public RemoveCustomerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBooking", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car rentalCar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public RentalServiceClient.RentalService.Customer renter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime endTime;
        
        public AddBookingRequest() {
        }
        
        public AddBookingRequest(RentalServiceClient.RentalService.Car rentalCar, RentalServiceClient.RentalService.Customer renter, System.DateTime startTime, System.DateTime endTime) {
            this.rentalCar = rentalCar;
            this.renter = renter;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBookingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBookingResponse {
        
        public AddBookingResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveBooking", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookingId;
        
        public RemoveBookingRequest() {
        }
        
        public RemoveBookingRequest(string bookingId) {
            this.bookingId = bookingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveBookingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveBookingResponse {
        
        public RemoveBookingResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking booking;
        
        public ReturnCarRequest() {
        }
        
        public ReturnCarRequest(RentalServiceClient.RentalService.Booking booking) {
            this.booking = booking;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnCarResponse {
        
        public ReturnCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckDate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime endDate;
        
        public CheckDateRequest() {
        }
        
        public CheckDateRequest(System.DateTime startDate, System.DateTime endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckDateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car[] CheckDateResult;
        
        public CheckDateResponse() {
        }
        
        public CheckDateResponse(RentalServiceClient.RentalService.Car[] CheckDateResult) {
            this.CheckDateResult = CheckDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string searchString;
        
        public GetCustomersRequest() {
        }
        
        public GetCustomersRequest(string searchString) {
            this.searchString = searchString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer[] GetCustomersResult;
        
        public GetCustomersResponse() {
        }
        
        public GetCustomersResponse(RentalServiceClient.RentalService.Customer[] GetCustomersResult) {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetCustomerByIdRequest() {
        }
        
        public GetCustomerByIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer GetCustomerByIdResult;
        
        public GetCustomerByIdResponse() {
        }
        
        public GetCustomerByIdResponse(RentalServiceClient.RentalService.Customer GetCustomerByIdResult) {
            this.GetCustomerByIdResult = GetCustomerByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public GetCustomersByNameRequest() {
        }
        
        public GetCustomersByNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomersByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomersByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer[] GetCustomersByNameResult;
        
        public GetCustomersByNameResponse() {
        }
        
        public GetCustomersByNameResponse(RentalServiceClient.RentalService.Customer[] GetCustomersByNameResult) {
            this.GetCustomersByNameResult = GetCustomersByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerByPhoneNumber", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByPhoneNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string number;
        
        public GetCustomerByPhoneNumberRequest() {
        }
        
        public GetCustomerByPhoneNumberRequest(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerByPhoneNumberResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByPhoneNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer GetCustomerByPhoneNumberResult;
        
        public GetCustomerByPhoneNumberResponse() {
        }
        
        public GetCustomerByPhoneNumberResponse(RentalServiceClient.RentalService.Customer GetCustomerByPhoneNumberResult) {
            this.GetCustomerByPhoneNumberResult = GetCustomerByPhoneNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerByEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        public GetCustomerByEmailRequest() {
        }
        
        public GetCustomerByEmailRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerByEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerByEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer GetCustomerByEmailResult;
        
        public GetCustomerByEmailResponse() {
        }
        
        public GetCustomerByEmailResponse(RentalServiceClient.RentalService.Customer GetCustomerByEmailResult) {
            this.GetCustomerByEmailResult = GetCustomerByEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerFromBooking", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerFromBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking booking;
        
        public GetCustomerFromBookingRequest() {
        }
        
        public GetCustomerFromBookingRequest(RentalServiceClient.RentalService.Booking booking) {
            this.booking = booking;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerFromBookingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomerFromBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer GetCustomerFromBookingResult;
        
        public GetCustomerFromBookingResponse() {
        }
        
        public GetCustomerFromBookingResponse(RentalServiceClient.RentalService.Customer GetCustomerFromBookingResult) {
            this.GetCustomerFromBookingResult = GetCustomerFromBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByReg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string regNumber;
        
        public GetCarByRegRequest() {
        }
        
        public GetCarByRegRequest(string regNumber) {
            this.regNumber = regNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarByRegResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarByRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car GetCarByRegResult;
        
        public GetCarByRegResponse() {
        }
        
        public GetCarByRegResponse(RentalServiceClient.RentalService.Car GetCarByRegResult) {
            this.GetCarByRegResult = GetCarByRegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByBrand", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByBrandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string brand;
        
        public GetCarsByBrandRequest() {
        }
        
        public GetCarsByBrandRequest(string brand) {
            this.brand = brand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByBrandResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByBrandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car[] GetCarsByBrandResult;
        
        public GetCarsByBrandResponse() {
        }
        
        public GetCarsByBrandResponse(RentalServiceClient.RentalService.Car[] GetCarsByBrandResult) {
            this.GetCarsByBrandResult = GetCarsByBrandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByYear", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int year;
        
        public GetCarsByYearRequest() {
        }
        
        public GetCarsByYearRequest(int year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByYearResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car[] GetCarsByYearResult;
        
        public GetCarsByYearResponse() {
        }
        
        public GetCarsByYearResponse(RentalServiceClient.RentalService.Car[] GetCarsByYearResult) {
            this.GetCarsByYearResult = GetCarsByYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByModel", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByModelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string model;
        
        public GetCarsByModelRequest() {
        }
        
        public GetCarsByModelRequest(string model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByModelResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByModelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car[] GetCarsByModelResult;
        
        public GetCarsByModelResponse() {
        }
        
        public GetCarsByModelResponse(RentalServiceClient.RentalService.Car[] GetCarsByModelResult) {
            this.GetCarsByModelResult = GetCarsByModelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByIsRented", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByIsRentedRequest {
        
        public GetCarsByIsRentedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarsByIsRentedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarsByIsRentedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car[] GetCarsByIsRentedResult;
        
        public GetCarsByIsRentedResponse() {
        }
        
        public GetCarsByIsRentedResponse(RentalServiceClient.RentalService.Car[] GetCarsByIsRentedResult) {
            this.GetCarsByIsRentedResult = GetCarsByIsRentedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarFromBooking", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarFromBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking booking;
        
        public GetCarFromBookingRequest() {
        }
        
        public GetCarFromBookingRequest(RentalServiceClient.RentalService.Booking booking) {
            this.booking = booking;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarFromBookingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarFromBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car GetCarFromBookingResult;
        
        public GetCarFromBookingResponse() {
        }
        
        public GetCarFromBookingResponse(RentalServiceClient.RentalService.Car GetCarFromBookingResult) {
            this.GetCarFromBookingResult = GetCarFromBookingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookingId;
        
        public GetBookingByIdRequest() {
        }
        
        public GetBookingByIdRequest(string bookingId) {
            this.bookingId = bookingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking GetBookingByIdResult;
        
        public GetBookingByIdResponse() {
        }
        
        public GetBookingByIdResponse(RentalServiceClient.RentalService.Booking GetBookingByIdResult) {
            this.GetBookingByIdResult = GetBookingByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Car car;
        
        public GetBookingsByCarRequest() {
        }
        
        public GetBookingsByCarRequest(RentalServiceClient.RentalService.Car car) {
            this.car = car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByCarResult;
        
        public GetBookingsByCarResponse() {
        }
        
        public GetBookingsByCarResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByCarResult) {
            this.GetBookingsByCarResult = GetBookingsByCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Customer customer;
        
        public GetBookingsByCustomerRequest() {
        }
        
        public GetBookingsByCustomerRequest(RentalServiceClient.RentalService.Customer customer) {
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerResult;
        
        public GetBookingsByCustomerResponse() {
        }
        
        public GetBookingsByCustomerResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerResult) {
            this.GetBookingsByCustomerResult = GetBookingsByCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomerEmail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        public GetBookingsByCustomerEmailRequest() {
        }
        
        public GetBookingsByCustomerEmailRequest(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomerEmailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerEmailResult;
        
        public GetBookingsByCustomerEmailResponse() {
        }
        
        public GetBookingsByCustomerEmailResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerEmailResult) {
            this.GetBookingsByCustomerEmailResult = GetBookingsByCustomerEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomerPhone", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string phone;
        
        public GetBookingsByCustomerPhoneRequest() {
        }
        
        public GetBookingsByCustomerPhoneRequest(string phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByCustomerPhoneResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByCustomerPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerPhoneResult;
        
        public GetBookingsByCustomerPhoneResponse() {
        }
        
        public GetBookingsByCustomerPhoneResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByCustomerPhoneResult) {
            this.GetBookingsByCustomerPhoneResult = GetBookingsByCustomerPhoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime end;
        
        public GetBookingsByTimeRequest() {
        }
        
        public GetBookingsByTimeRequest(System.DateTime start, System.DateTime end) {
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByTimeResult;
        
        public GetBookingsByTimeResponse() {
        }
        
        public GetBookingsByTimeResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByTimeResult) {
            this.GetBookingsByTimeResult = GetBookingsByTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByIsNotReturned", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByIsNotReturnedRequest {
        
        public GetBookingsByIsNotReturnedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBookingsByIsNotReturnedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBookingsByIsNotReturnedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RentalServiceClient.RentalService.Booking[] GetBookingsByIsNotReturnedResult;
        
        public GetBookingsByIsNotReturnedResponse() {
        }
        
        public GetBookingsByIsNotReturnedResponse(RentalServiceClient.RentalService.Booking[] GetBookingsByIsNotReturnedResult) {
            this.GetBookingsByIsNotReturnedResult = GetBookingsByIsNotReturnedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarRequestObject", WrapperNamespace="http://localhost:8080/Car", IsWrapped=true)]
    public partial class CarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://localhost:8080/Car")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=0)]
        public string CarId;
        
        public CarRequest() {
        }
        
        public CarRequest(string LicenseKey, string CarId) {
            this.LicenseKey = LicenseKey;
            this.CarId = CarId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarInfoObject", WrapperNamespace="http://localhost:8080/Car", IsWrapped=true)]
    public partial class CarInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=0)]
        public string RegNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=1)]
        public string Brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=2)]
        public int Year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=3)]
        public string Model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8080/Car", Order=4)]
        public bool IsRented;
        
        public CarInfo() {
        }
        
        public CarInfo(string RegNumber, string Brand, int Year, string Model, bool IsRented) {
            this.RegNumber = RegNumber;
            this.Brand = Brand;
            this.Year = Year;
            this.Model = Model;
            this.IsRented = IsRented;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCarResponse {
        
        public SaveCarResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalServiceTestChannel : RentalServiceClient.RentalService.IRentalServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalServiceTestClient : System.ServiceModel.ClientBase<RentalServiceClient.RentalService.IRentalServiceTest>, RentalServiceClient.RentalService.IRentalServiceTest {
        
        public RentalServiceTestClient() {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RentalServiceClient.RentalService.AddCarResponse AddCar(RentalServiceClient.RentalService.AddCarRequest request) {
            return base.Channel.AddCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddCarResponse> AddCarAsync(RentalServiceClient.RentalService.AddCarRequest request) {
            return base.Channel.AddCarAsync(request);
        }
        
        public RentalServiceClient.RentalService.RemoveCarResponse RemoveCar(RentalServiceClient.RentalService.RemoveCarRequest request) {
            return base.Channel.RemoveCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveCarResponse> RemoveCarAsync(RentalServiceClient.RentalService.RemoveCarRequest request) {
            return base.Channel.RemoveCarAsync(request);
        }
        
        public RentalServiceClient.RentalService.AddCustomerResponse AddCustomer(RentalServiceClient.RentalService.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddCustomerResponse> AddCustomerAsync(RentalServiceClient.RentalService.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public RentalServiceClient.RentalService.EditCustomerResponse EditCustomer(RentalServiceClient.RentalService.EditCustomerRequest request) {
            return base.Channel.EditCustomer(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.EditCustomerResponse> EditCustomerAsync(RentalServiceClient.RentalService.EditCustomerRequest request) {
            return base.Channel.EditCustomerAsync(request);
        }
        
        public RentalServiceClient.RentalService.RemoveCustomerResponse RemoveCustomer(RentalServiceClient.RentalService.RemoveCustomerRequest request) {
            return base.Channel.RemoveCustomer(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveCustomerResponse> RemoveCustomerAsync(RentalServiceClient.RentalService.RemoveCustomerRequest request) {
            return base.Channel.RemoveCustomerAsync(request);
        }
        
        public RentalServiceClient.RentalService.AddBookingResponse AddBooking(RentalServiceClient.RentalService.AddBookingRequest request) {
            return base.Channel.AddBooking(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.AddBookingResponse> AddBookingAsync(RentalServiceClient.RentalService.AddBookingRequest request) {
            return base.Channel.AddBookingAsync(request);
        }
        
        public RentalServiceClient.RentalService.RemoveBookingResponse RemoveBooking(RentalServiceClient.RentalService.RemoveBookingRequest request) {
            return base.Channel.RemoveBooking(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.RemoveBookingResponse> RemoveBookingAsync(RentalServiceClient.RentalService.RemoveBookingRequest request) {
            return base.Channel.RemoveBookingAsync(request);
        }
        
        public RentalServiceClient.RentalService.ReturnCarResponse ReturnCar(RentalServiceClient.RentalService.ReturnCarRequest request) {
            return base.Channel.ReturnCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.ReturnCarResponse> ReturnCarAsync(RentalServiceClient.RentalService.ReturnCarRequest request) {
            return base.Channel.ReturnCarAsync(request);
        }
        
        public RentalServiceClient.RentalService.CheckDateResponse CheckDate(RentalServiceClient.RentalService.CheckDateRequest request) {
            return base.Channel.CheckDate(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.CheckDateResponse> CheckDateAsync(RentalServiceClient.RentalService.CheckDateRequest request) {
            return base.Channel.CheckDateAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomersResponse GetCustomers(RentalServiceClient.RentalService.GetCustomersRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomersResponse> GetCustomersAsync(RentalServiceClient.RentalService.GetCustomersRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomerByIdResponse GetCustomerById(RentalServiceClient.RentalService.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerById(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByIdResponse> GetCustomerByIdAsync(RentalServiceClient.RentalService.GetCustomerByIdRequest request) {
            return base.Channel.GetCustomerByIdAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomersByNameResponse GetCustomersByName(RentalServiceClient.RentalService.GetCustomersByNameRequest request) {
            return base.Channel.GetCustomersByName(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomersByNameResponse> GetCustomersByNameAsync(RentalServiceClient.RentalService.GetCustomersByNameRequest request) {
            return base.Channel.GetCustomersByNameAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomerByPhoneNumberResponse GetCustomerByPhoneNumber(RentalServiceClient.RentalService.GetCustomerByPhoneNumberRequest request) {
            return base.Channel.GetCustomerByPhoneNumber(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByPhoneNumberResponse> GetCustomerByPhoneNumberAsync(RentalServiceClient.RentalService.GetCustomerByPhoneNumberRequest request) {
            return base.Channel.GetCustomerByPhoneNumberAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomerByEmailResponse GetCustomerByEmail(RentalServiceClient.RentalService.GetCustomerByEmailRequest request) {
            return base.Channel.GetCustomerByEmail(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerByEmailResponse> GetCustomerByEmailAsync(RentalServiceClient.RentalService.GetCustomerByEmailRequest request) {
            return base.Channel.GetCustomerByEmailAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCustomerFromBookingResponse GetCustomerFromBooking(RentalServiceClient.RentalService.GetCustomerFromBookingRequest request) {
            return base.Channel.GetCustomerFromBooking(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCustomerFromBookingResponse> GetCustomerFromBookingAsync(RentalServiceClient.RentalService.GetCustomerFromBookingRequest request) {
            return base.Channel.GetCustomerFromBookingAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarByRegResponse GetCarByReg(RentalServiceClient.RentalService.GetCarByRegRequest request) {
            return base.Channel.GetCarByReg(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarByRegResponse> GetCarByRegAsync(RentalServiceClient.RentalService.GetCarByRegRequest request) {
            return base.Channel.GetCarByRegAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarsByBrandResponse GetCarsByBrand(RentalServiceClient.RentalService.GetCarsByBrandRequest request) {
            return base.Channel.GetCarsByBrand(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByBrandResponse> GetCarsByBrandAsync(RentalServiceClient.RentalService.GetCarsByBrandRequest request) {
            return base.Channel.GetCarsByBrandAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarsByYearResponse GetCarsByYear(RentalServiceClient.RentalService.GetCarsByYearRequest request) {
            return base.Channel.GetCarsByYear(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByYearResponse> GetCarsByYearAsync(RentalServiceClient.RentalService.GetCarsByYearRequest request) {
            return base.Channel.GetCarsByYearAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarsByModelResponse GetCarsByModel(RentalServiceClient.RentalService.GetCarsByModelRequest request) {
            return base.Channel.GetCarsByModel(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByModelResponse> GetCarsByModelAsync(RentalServiceClient.RentalService.GetCarsByModelRequest request) {
            return base.Channel.GetCarsByModelAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarsByIsRentedResponse GetCarsByIsRented(RentalServiceClient.RentalService.GetCarsByIsRentedRequest request) {
            return base.Channel.GetCarsByIsRented(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarsByIsRentedResponse> GetCarsByIsRentedAsync(RentalServiceClient.RentalService.GetCarsByIsRentedRequest request) {
            return base.Channel.GetCarsByIsRentedAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetCarFromBookingResponse GetCarFromBooking(RentalServiceClient.RentalService.GetCarFromBookingRequest request) {
            return base.Channel.GetCarFromBooking(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetCarFromBookingResponse> GetCarFromBookingAsync(RentalServiceClient.RentalService.GetCarFromBookingRequest request) {
            return base.Channel.GetCarFromBookingAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingByIdResponse GetBookingById(RentalServiceClient.RentalService.GetBookingByIdRequest request) {
            return base.Channel.GetBookingById(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingByIdResponse> GetBookingByIdAsync(RentalServiceClient.RentalService.GetBookingByIdRequest request) {
            return base.Channel.GetBookingByIdAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByCarResponse GetBookingsByCar(RentalServiceClient.RentalService.GetBookingsByCarRequest request) {
            return base.Channel.GetBookingsByCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCarResponse> GetBookingsByCarAsync(RentalServiceClient.RentalService.GetBookingsByCarRequest request) {
            return base.Channel.GetBookingsByCarAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByCustomerResponse GetBookingsByCustomer(RentalServiceClient.RentalService.GetBookingsByCustomerRequest request) {
            return base.Channel.GetBookingsByCustomer(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerResponse> GetBookingsByCustomerAsync(RentalServiceClient.RentalService.GetBookingsByCustomerRequest request) {
            return base.Channel.GetBookingsByCustomerAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByCustomerEmailResponse GetBookingsByCustomerEmail(RentalServiceClient.RentalService.GetBookingsByCustomerEmailRequest request) {
            return base.Channel.GetBookingsByCustomerEmail(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerEmailResponse> GetBookingsByCustomerEmailAsync(RentalServiceClient.RentalService.GetBookingsByCustomerEmailRequest request) {
            return base.Channel.GetBookingsByCustomerEmailAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByCustomerPhoneResponse GetBookingsByCustomerPhone(RentalServiceClient.RentalService.GetBookingsByCustomerPhoneRequest request) {
            return base.Channel.GetBookingsByCustomerPhone(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByCustomerPhoneResponse> GetBookingsByCustomerPhoneAsync(RentalServiceClient.RentalService.GetBookingsByCustomerPhoneRequest request) {
            return base.Channel.GetBookingsByCustomerPhoneAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByTimeResponse GetBookingsByTime(RentalServiceClient.RentalService.GetBookingsByTimeRequest request) {
            return base.Channel.GetBookingsByTime(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByTimeResponse> GetBookingsByTimeAsync(RentalServiceClient.RentalService.GetBookingsByTimeRequest request) {
            return base.Channel.GetBookingsByTimeAsync(request);
        }
        
        public RentalServiceClient.RentalService.GetBookingsByIsNotReturnedResponse GetBookingsByIsNotReturned(RentalServiceClient.RentalService.GetBookingsByIsNotReturnedRequest request) {
            return base.Channel.GetBookingsByIsNotReturned(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.GetBookingsByIsNotReturnedResponse> GetBookingsByIsNotReturnedAsync(RentalServiceClient.RentalService.GetBookingsByIsNotReturnedRequest request) {
            return base.Channel.GetBookingsByIsNotReturnedAsync(request);
        }
        
        public RentalServiceClient.RentalService.CarInfo GetCar(RentalServiceClient.RentalService.CarRequest request) {
            return base.Channel.GetCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.CarInfo> GetCarAsync(RentalServiceClient.RentalService.CarRequest request) {
            return base.Channel.GetCarAsync(request);
        }
        
        public RentalServiceClient.RentalService.SaveCarResponse SaveCar(RentalServiceClient.RentalService.CarInfo request) {
            return base.Channel.SaveCar(request);
        }
        
        public System.Threading.Tasks.Task<RentalServiceClient.RentalService.SaveCarResponse> SaveCarAsync(RentalServiceClient.RentalService.CarInfo request) {
            return base.Channel.SaveCarAsync(request);
        }
    }
}
