//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalServiceClient.RentalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalService.IRentalServiceTest")]
    public interface IRentalServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCar", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCarResponse")]
        void AddCar(string regNumber, string brand, int year, string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalServiceTest/AddCar", ReplyAction="http://tempuri.org/IRentalServiceTest/AddCarResponse")]
        System.Threading.Tasks.Task AddCarAsync(string regNumber, string brand, int year, string model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalServiceTestChannel : RentalServiceClient.RentalService.IRentalServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalServiceTestClient : System.ServiceModel.ClientBase<RentalServiceClient.RentalService.IRentalServiceTest>, RentalServiceClient.RentalService.IRentalServiceTest {
        
        public RentalServiceTestClient() {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCar(string regNumber, string brand, int year, string model) {
            base.Channel.AddCar(regNumber, brand, year, model);
        }
        
        public System.Threading.Tasks.Task AddCarAsync(string regNumber, string brand, int year, string model) {
            return base.Channel.AddCarAsync(regNumber, brand, year, model);
        }
    }
}
